import { useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/header';
import Nav from '@/components/nav';
import FileDrop from '@/components/filedrop';
import Quick_Action from '@/components/quick_action';

const handleFileDropped = (file: File) => {
  console.log('File dropped:', file);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='grid grid-cols-[200px_minmax(500px,_1fr)]'>
        <div>
          <Nav></Nav>
        </div>
        <div>
          <Header></Header>
          <main className='bg-gray-900 h-full grid grid-rows-2'>
            <section className='grid grid-cols-2 gap-10 px-10'>
              <Quick_Action></Quick_Action>
              <FileDrop onFileDropped={handleFileDropped}></FileDrop>
            </section>
            <section></section>
          </main>
        </div>
      </div>
    </>
  );
}
