import { useEffect, useState } from 'react';
import Head from 'next/head';
import Header from '@/components/header';
import Nav from '@/components/nav';
import FileDrop from '@/components/filedrop';
import Quick_Action from '@/components/quick_action';
import { useSession } from 'next-auth/react';
import Login from '@/pages/login';
import Settings from '@/pages/settings';

const handleFileDropped = (file: File) => {
  console.log('File dropped:', file);
};

export default function Home() {
  const { data: session, status } = useSession();
  const loading = status === 'loading';

  if (loading) {
    return (
      <div className='min-h-screen bg-gray-800 grid grid-cols-1 items-center justify-center'>
        <div className='mx-auto text-center text-white'>Loading...</div>
      </div>
    );
  }

  if (!session) {
    return <Login />;
  }

  return (
    <>
      <Head>
        <title>Tauri Next Starter</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='grid grid-cols-[200px_minmax(500px,_1fr)]'>
        <div>
          <Nav></Nav>
        </div>
        <div>
          <Header />
          <main className='bg-gray-900 h-full grid grid-rows-2'>
            <section className='grid grid-cols-2 gap-10 px-10'>
              <Quick_Action />
              <FileDrop onFileDropped={handleFileDropped}></FileDrop>
            </section>
            <section></section>
          </main>
        </div>
      </div>
    </>
  );
}
